REPORT ZCOPA001 NO STANDARD PAGE HEADING.
*
************************************************************************
*
*  AUTHOR:      MOHAMMAD KHAN
*  DATE:        FEBRUARY, 2002.
*  Description:
*     - The purpose of this program is to produce consolidated data
*       from the table CE11100. This program is using ALV technique.
*
*
*
************************************************************************
* DB-Table
TABLES CE11100.

* Type-pool of ALV
TYPE-POOLS: SLIS.

* Report Selections
PARAMETERS:     P_BUKRS LIKE CE11100-BUKRS OBLIGATORY    DEFAULT 'UGL',
                P_KOKRS LIKE CE11100-KOKRS OBLIGATORY    DEFAULT '10',
                P_PALGR LIKE CE11100-PALEDGER OBLIGATORY,
                P_PLIKZ LIKE CE11100-PLIKZ    OBLIGATORY DEFAULT '0'.

SELECT-OPTIONS: S_PERIO FOR  CE11100-PERIO    OBLIGATORY,
                S_VKORG FOR  CE11100-VKORG    OBLIGATORY,
                S_VRGAR FOR  CE11100-VRGAR    OBLIGATORY,
                S_PRDHA FOR  CE11100-PRDHA OBLIGATORY DEFAULT
                               '00150000100010' TO '00179999999999'.
SELECTION-SCREEN SKIP 1.

DATA: GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.

* Data to be displayed
DATA:
  BEGIN OF ITABLE OCCURS 0,
        PERIO   LIKE CE11100-PERIO,
        KNDNR   LIKE CE11100-KNDNR,
        WWSBU   LIKE CE11100-WWSBU,
        WWSCT   LIKE CE11100-WWSCT,
        WWSEG   LIKE CE11100-WWSEG,
        WWRAT   LIKE CE11100-WWRAT,
        WWSER   LIKE CE11100-WWSER,
        WERKS   LIKE CE11100-WERKS,
        WWDVS   LIKE CE11100-WWDVS,
        WWRGN   LIKE CE11100-WWRGN,
        ARTNR   LIKE CE11100-ARTNR,
        PRDHA   LIKE CE11100-PRDHA,
        VVBRV   LIKE CE11100-VVBRV,
        VVBVL   LIKE CE11100-VVBVL,
        VVCUT   LIKE CE11100-VVCUT,
  END   OF ITABLE.

DATA:
  BEGIN OF FTABLE OCCURS 0,
        PERIO   LIKE CE11100-PERIO,
        BLANK1(5),
        KNDNR   LIKE CE11100-KNDNR,
        WWSBU   LIKE CE11100-WWSBU,
        BLANK2(5),
        BLANK3(5),
        WWSCT   LIKE CE11100-WWSCT,
        WWSEG   LIKE CE11100-WWSEG,
        WWRAT   LIKE CE11100-WWRAT,
        WWSER   LIKE CE11100-WWSER,
        WERKS   LIKE CE11100-WERKS,
        BLANK4(5),
        WWDVS   LIKE CE11100-WWDVS,
        WWRGN   LIKE CE11100-WWRGN,
        ARTNR   LIKE CE11100-ARTNR,
        PRDHA   LIKE CE11100-PRDHA,
        VVBRV   LIKE CE11100-VVBRV,
        VVBVL   LIKE CE11100-VVBVL,
        VVCUT   LIKE CE11100-VVCUT,
  END   OF FTABLE.

DATA: GS_EXTRACT1 LIKE SY-REPID.
DATA: GS_EXTRACT2 LIKE DISEXTRACT.
*---------------------------------------------------------------------*
*
INITIALIZATION.

PERFORM FIELDCAT_INIT  USING GT_FIELDCAT[].

START-OF-SELECTION.

* DB Selection
SELECT  PERIO KNDNR WWSBU WWSCT WWSEG WWRAT WWSER WERKS
        WWDVS WWRGN ARTNR PRDHA VVBRV VVBVL VVCUT
  INTO  TABLE ITABLE
  FROM  CE11100
 WHERE  BUKRS = P_BUKRS
   AND  KOKRS = P_KOKRS
   AND  PALEDGER = P_PALGR
   AND  PLIKZ    = P_PLIKZ
   AND  PERIO   IN S_PERIO
   AND  VRGAR   IN S_VRGAR
   AND  VKORG   IN S_VKORG
   AND  PRDHA   IN S_PRDHA.

   IF ITABLE[] IS INITIAL.
      WRITE: /1 'NO DATA SELECTED'.
      STOP.
   ENDIF.

  SORT ITABLE.

  LOOP AT ITABLE.
    MOVE-CORRESPONDING ITABLE TO FTABLE.
    COLLECT FTABLE.
    CLEAR   FTABLE.
  ENDLOOP.

* Call ABAP/4 List Viewer
  MOVE SY-REPID TO GS_EXTRACT1.
  CALL FUNCTION 'REUSE_ALV_LIST_DISPLAY'
       EXPORTING
            I_CALLBACK_PROGRAM = GS_EXTRACT1
*            I_STRUCTURE_NAME = 'CE11100'
            IT_FIELDCAT              = GT_FIELDCAT[]
            I_SAVE           = 'A'
       TABLES
            T_OUTTAB         = FTABLE.

FORM FIELDCAT_INIT USING RT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.
  DATA: LS_FIELDCAT TYPE SLIS_FIELDCAT_ALV.

  CLEAR LS_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'PERIO'.
  LS_FIELDCAT-COL_POS       = 1.
  LS_FIELDCAT-REPTEXT_DDIC  = 'PERIOD'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'BLANK1'.
  LS_FIELDCAT-COL_POS       = 2.
  LS_FIELDCAT-REPTEXT_DDIC  = 'BLANK1'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'KNDNR'.
  LS_FIELDCAT-COL_POS       = 3.
  LS_FIELDCAT-REPTEXT_DDIC  = 'CUSTOMER'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'WWSBU'.
  LS_FIELDCAT-COL_POS       = 4.
  LS_FIELDCAT-REPTEXT_DDIC  = 'S.B.UNIT'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'BLANK2'.
  LS_FIELDCAT-COL_POS       = 5.
  LS_FIELDCAT-REPTEXT_DDIC  = 'BLANK2'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'BLANK3'.
  LS_FIELDCAT-COL_POS       = 6.
  LS_FIELDCAT-REPTEXT_DDIC  = 'BLANK3'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

*  LS_FIELDCAT-FIELDNAME     = 'WWSCT'.
*  LS_FIELDCAT-COL_POS       = 5.
*  LS_FIELDCAT-REPTEXT_DDIC  = 'SECTOR'.
*  APPEND LS_FIELDCAT TO  RT_FIELDCAT.
*
*  LS_FIELDCAT-FIELDNAME     = 'WWSEG'.
*  LS_FIELDCAT-COL_POS       = 6.
*  LS_FIELDCAT-REPTEXT_DDIC  = 'SEGMENT'.
*  APPEND LS_FIELDCAT TO  RT_FIELDCAT.
*
  LS_FIELDCAT-FIELDNAME     = 'WWRAT'.
  LS_FIELDCAT-COL_POS       = 7.
  LS_FIELDCAT-REPTEXT_DDIC  = 'RATE CLASS'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'WWSER'.
  LS_FIELDCAT-COL_POS       = 8.
  LS_FIELDCAT-REPTEXT_DDIC  = 'S.CLASS'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'WERKS'.
  LS_FIELDCAT-COL_POS       = 9.
  LS_FIELDCAT-REPTEXT_DDIC  = 'PLANT'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'BLANK4'.
  LS_FIELDCAT-COL_POS       = 10.
  LS_FIELDCAT-REPTEXT_DDIC  = 'BLANK4'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'WWDVS'.
  LS_FIELDCAT-COL_POS       = 11.
  LS_FIELDCAT-REPTEXT_DDIC  = 'DIVISION'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'WWRGN'.
  LS_FIELDCAT-COL_POS       = 12.
  LS_FIELDCAT-REPTEXT_DDIC  = 'REGION'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'ARTNR'.
  LS_FIELDCAT-COL_POS       = 13.
  LS_FIELDCAT-REPTEXT_DDIC  = 'PROD #'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'PRDHA'.
  LS_FIELDCAT-COL_POS       = 14.
  LS_FIELDCAT-REPTEXT_DDIC  = 'P. HIERARCHY'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'VVBRV'.
  LS_FIELDCAT-COL_POS       = 16.
  LS_FIELDCAT-REPTEXT_DDIC  = 'BILLED REV'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'VVBVL'.
  LS_FIELDCAT-COL_POS       = 17.
  LS_FIELDCAT-REPTEXT_DDIC  = 'BILLED VOL'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME     = 'VVCUT'.
  LS_FIELDCAT-COL_POS       = 18.
  LS_FIELDCAT-REPTEXT_DDIC  = '# OF CUSTOMERS'.
  APPEND LS_FIELDCAT TO  RT_FIELDCAT.

ENDFORM.

